version: "3"
services:
  datadog:
    build: ./docker/datadog-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./logs/:/var/log/akka-datadog-sandbox
    environment:
      DD_API_KEY: $AKKA_DATADOG_SANDBOX_DD_API_KEY
      DD_APM_ENABLED: true
      DD_APM_NON_LOCAL_TRAFFIC: true
      DD_LOGS_ENABLED: true
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
    labels:
      com.datadog.ad.logs: '[{"source": "java", "service": "akka-datadog-sandbox", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    ports:
      - "8125:8125/udp"
      - "8126:8126/tcp"
